## APPLICATION CONFIG # --------------------------------------------

# Used to enable/disable test code and/or data during development
test_mode: false

# Default Title for HTML pages
web:
  title:       "FuelMe"
  description: "FuelMe"
  keywords:    "skywyre"
  author:      "Rahmal Conda"
  robots:      "noodp,noydir"
  viewport:    "initial-scale=1.0, user-scalable=no"
  copyright:   "&copy; 2012 Fuel Choice"

navbar:
  - ['/how_it_works', 'HOW IT WORKS',       [home, how_it_works] ]
  - ['/loans',        'PERSONAL LOANS',     [home, loans]        ]
  - ['/investors',    'INVESTING',          [home, investors]    ]
  - ['/calculator',   'SAVINGS CALCULATOR', [home, calculator]   ]
  - ['/about',        'ABOUT US',           [home, about]        ]
  - ['/contact',      'CONTACT US',         [home, contact]      ]
  - ['/help',         'HELP',               [home, help]         ]
 
favicon:
  ico: 'favicon.ico'
  png: '/assets/fuelme-icon.png'

analytics:
  google:
    enabled: false
    uid: 'UA-19146385-1'

# Default Pagination Settings
pagination_defaults:
  page: 1
  per_page: 10

# Regular expressions for validation
regexp:
  email: !ruby/regexp '/^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i'
  phone: !ruby/regexp '/^(?:(\d)[ \-\.]?)?(?:\(?(\d{3})\)?[ \-\.])?(\d{3})[ \-\.](\d{4})(?: ?x?(\d+))?$/'
  alias: !ruby/regexp '/^[A-Za-z0-9.&]*\z/'
  name:  !ruby/regexp '/^[A-Za-z]*[\ |\-]?[A-Za-z]*$/'
  phone_stripped: !ruby/regexp '/(\d{3})(\d{3})(\d{4})/'
  url: !ruby/regexp '/(http|https):\/\/((\w+\.){1,3}\w+\/\w+[^\s]+)/'  
# Providers of oauth-based external authentication
account_providers: [facebook]

# Root Subdomains: Subdomains that should be routed to root url, i.e. 'www'
root_subdomains: [www, dev]
